spring:
  application:
    name: authenticated_service
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform:
      org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    password: root
    url: jdbc:h2:mem:auth_service
    username: root