spring:
  application:
    name: authenticated_service
  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: postgres
    driverClassName: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5432/users
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
allowOrigin: http://localhost