server:
  port:
    8060

spring:
  main:
    web-application-type: reactive

  application:
    name: fitness-service-config-server

  profiles:
    active:
      - git
  cloud:
    config:
      server:
        git:
          uri:
          default-label: main
          clone-on-start: true