version: "3.9"

services:
  auth-db:
    container_name: auth-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - services-network
    
  article-db:
    container_name: article-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: articles
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - services-network
      
  config-service:
    container_name: config
    healthcheck:
      test: ["CMD", "--interval=4", "--timeout=16", "curl -f http://localhost:8060/actuator/health"]
    build:
      context: ../back/fitnessServiceConfig/docker
    restart: always
    ports:
      - 8060:8060
    networks:
      - services-network
      
  discovery-service:
    container_name: discovery
    healthcheck:
      test: ["CMD", "--interval=4", "--timeout=16", "curl -f http://localhost:8090/actuator/health"]
    build:
      context: ../back/fitnessServiceDiscovery/docker
    restart: always
    ports:
      - 8090:8090
    depends_on:
      - config-service
    networks:
      - services-network
            
  gateway-service:
    container_name: gateway
    build:
      context: ../back/fitnessServiceGateway/docker
    restart: always
    ports:
      - 8100:8100
    depends_on:
      - config-service
      - discovery-service
    networks:
      - services-network
            
  auth-service:
    container_name: auth
    build:
      context: ../back/fitnessServiceAuth/docker
    restart: always
    ports:
      - 8070:8070
    depends_on:
      - config-service
      - discovery-service
      - auth-db
    networks:
      - services-network
            
  article-service:
    container_name: article
    build:
      context: ../back/fitnessServiceArticles/docker
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - config-service
      - discovery-service
      - article-db
    networks:
      - services-network
            
  video-service:
    container_name: video
    build:
      context: ../back/fitnessServiceVideo/docker
    restart: always
    ports:
      - 8110:8110
    depends_on:
      - config-service
      - discovery-service
    networks:
      - services-network
            
  chat-service:
    container_name: chat
    build:
      context: ../back/fitnessServiceChat/docker
    restart: always
    ports:
      - 8120:8120
    depends_on:
      - config-service
      - discovery-service
    networks:
      - services-network
            
  web-service:
    container_name: web
    image: nginx
    volumes:
      - ../back/images:/usr/share/nginx/images
      - ../static/pages:/usr/share/nginx/html:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"

networks:
  services-network:
    driver: bridge