version: "3.9"

services:
  auth-db:
    container_name: auth-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - services-network
    
  article-db:
    container_name: article-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: articles
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - services-network
      
  config-services:
    container_name: config
    build:
      context: ../back/fitnessServiceConfig/docker
    restart: always
    networks:
      - services-network
            
  discovery-services:
    container_name: discovery
    build:
      context: ../back/fitnessServiceDiscovery/docker
    restart: always
    networks:
      - services-network
            
  gateway-services:
    container_name: gateway
    build:
      context: ../back/fitnessServiceGateway/docker
    restart: always
    networks:
      - services-network
            
  auth-services:
    container_name: auth
    build:
      context: ../back/fitnessServiceAuth/docker
    restart: always
    networks:
      - services-network
            
  article-services:
    container_name: article
    build:
      context: ../back/fitnessServiceArticles/docker
    restart: always
    networks:
      - services-network
            
  video-services:
    container_name: video
    build:
      context: ../back/fitnessServiceVideo/docker
    restart: always
    networks:
      - services-network
            
  chat-services:
    container_name: chat
    build:
      context: ../back/fitnessServiceChat/docker
    restart: always
    networks:
      - services-network
            
  web-services:
    container_name: web
    image: nginx
    volumes:
      - ../back/images:/usr/share/nginx/images
      - ../static/pages:/usr/share/nginx/html:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"

networks:
  services-network:
    driver: bridge