spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddlAuto: none

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5432/fitness_blog
    username: root